// Code generated by command: go run asm_avo_generator.go -out operation.s -stubs operation_stub.go. DO NOT EDIT.

package matrix

func multipleMicroCore(a []float32, b []float32, c []float32)

func MultipleMicroCore16x8(a []float32, b []float32, c []float32)

func MultipleMicroCore24x8(a []float32, b []float32, c []float32)

func MultipleMicroCore4x5by4x4(a []float64, b []float64, c []float64)
